
ALTER PROCEDURE USUARIO_CRIAR_CONTA (@NOME VARCHAR(100), 
                                      @EMAIL VARCHAR(100), 
									  @SENHA VARCHAR(50), 
									  @COD_USUARIO INT OUT, 
									  @RETORNO VARCHAR(1000) OUT
) AS
DECLARE @COD_EMPRESA INT
BEGIN TRY
		SET @RETORNO = 'OK'

		--CADASTRA NOVA EMPRESA AUTOMATICAMENTE--
		INSERT INTO TAB_EMPRESA(NOME, CNPJ_CPF)
		VALUES(@NOME, '')

		--BUSCA COD_EMPRESA GERADO--
		SET @COD_EMPRESA = SCOPE_IDENTITY() 

		--CALCULA SEQ USUARIO--
		SELECT @COD_USUARIO = ISNULL(MAX(COD_USUARIO), 0)
		FROM   TAB_USUARIO
		WHERE  COD_EMPRESA = @COD_EMPRESA

		SET @COD_USUARIO = @COD_USUARIO + 1

		INSERT INTO TAB_USUARIO(COD_EMPRESA, COD_USUARIO, NOME, EMAIL, SENHA)
		VALUES(@COD_EMPRESA, @COD_USUARIO, @NOME, @EMAIL, @SENHA)
	
END TRY

BEGIN CATCH
		SET @RETORNO = 'Ocorreu um erro ao criar usuário'
END CATCH
